/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppWishlistRouteImport } from './routes/_app/wishlist'
import { Route as AppStatsRouteImport } from './routes/_app/stats'
import { Route as AppShelvesRouteImport } from './routes/_app/shelves'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppOracleRouteImport } from './routes/_app/oracle'
import { Route as AppAddRouteImport } from './routes/_app/add'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppPeoplePersonRouteImport } from './routes/_app/people.$person'
import { Route as AppFilmsFilmIdRouteImport } from './routes/_app/films.$filmId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWishlistRoute = AppWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => AppRoute,
} as any)
const AppStatsRoute = AppStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AppRoute,
} as any)
const AppShelvesRoute = AppShelvesRouteImport.update({
  id: '/shelves',
  path: '/shelves',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppOracleRoute = AppOracleRouteImport.update({
  id: '/oracle',
  path: '/oracle',
  getParentRoute: () => AppRoute,
} as any)
const AppAddRoute = AppAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPeoplePersonRoute = AppPeoplePersonRouteImport.update({
  id: '/people/$person',
  path: '/people/$person',
  getParentRoute: () => AppRoute,
} as any)
const AppFilmsFilmIdRoute = AppFilmsFilmIdRouteImport.update({
  id: '/films/$filmId',
  path: '/films/$filmId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/add': typeof AppAddRoute
  '/oracle': typeof AppOracleRoute
  '/settings': typeof AppSettingsRoute
  '/shelves': typeof AppShelvesRoute
  '/stats': typeof AppStatsRoute
  '/wishlist': typeof AppWishlistRoute
  '/films/$filmId': typeof AppFilmsFilmIdRoute
  '/people/$person': typeof AppPeoplePersonRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/add': typeof AppAddRoute
  '/oracle': typeof AppOracleRoute
  '/settings': typeof AppSettingsRoute
  '/shelves': typeof AppShelvesRoute
  '/stats': typeof AppStatsRoute
  '/wishlist': typeof AppWishlistRoute
  '/': typeof AppIndexRoute
  '/films/$filmId': typeof AppFilmsFilmIdRoute
  '/people/$person': typeof AppPeoplePersonRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_app/add': typeof AppAddRoute
  '/_app/oracle': typeof AppOracleRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/shelves': typeof AppShelvesRoute
  '/_app/stats': typeof AppStatsRoute
  '/_app/wishlist': typeof AppWishlistRoute
  '/_app/': typeof AppIndexRoute
  '/_app/films/$filmId': typeof AppFilmsFilmIdRoute
  '/_app/people/$person': typeof AppPeoplePersonRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/add'
    | '/oracle'
    | '/settings'
    | '/shelves'
    | '/stats'
    | '/wishlist'
    | '/films/$filmId'
    | '/people/$person'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/add'
    | '/oracle'
    | '/settings'
    | '/shelves'
    | '/stats'
    | '/wishlist'
    | '/'
    | '/films/$filmId'
    | '/people/$person'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/signup'
    | '/_app/add'
    | '/_app/oracle'
    | '/_app/settings'
    | '/_app/shelves'
    | '/_app/stats'
    | '/_app/wishlist'
    | '/_app/'
    | '/_app/films/$filmId'
    | '/_app/people/$person'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wishlist': {
      id: '/_app/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof AppWishlistRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stats': {
      id: '/_app/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof AppStatsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shelves': {
      id: '/_app/shelves'
      path: '/shelves'
      fullPath: '/shelves'
      preLoaderRoute: typeof AppShelvesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/oracle': {
      id: '/_app/oracle'
      path: '/oracle'
      fullPath: '/oracle'
      preLoaderRoute: typeof AppOracleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/add': {
      id: '/_app/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AppAddRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/people/$person': {
      id: '/_app/people/$person'
      path: '/people/$person'
      fullPath: '/people/$person'
      preLoaderRoute: typeof AppPeoplePersonRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/films/$filmId': {
      id: '/_app/films/$filmId'
      path: '/films/$filmId'
      fullPath: '/films/$filmId'
      preLoaderRoute: typeof AppFilmsFilmIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAddRoute: typeof AppAddRoute
  AppOracleRoute: typeof AppOracleRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppShelvesRoute: typeof AppShelvesRoute
  AppStatsRoute: typeof AppStatsRoute
  AppWishlistRoute: typeof AppWishlistRoute
  AppIndexRoute: typeof AppIndexRoute
  AppFilmsFilmIdRoute: typeof AppFilmsFilmIdRoute
  AppPeoplePersonRoute: typeof AppPeoplePersonRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAddRoute: AppAddRoute,
  AppOracleRoute: AppOracleRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppShelvesRoute: AppShelvesRoute,
  AppStatsRoute: AppStatsRoute,
  AppWishlistRoute: AppWishlistRoute,
  AppIndexRoute: AppIndexRoute,
  AppFilmsFilmIdRoute: AppFilmsFilmIdRoute,
  AppPeoplePersonRoute: AppPeoplePersonRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
